version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.10.0

executors:
  my-executor:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dulrey/test-repo

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: mkdir -p /go/src/github.com/dulrey/workspace
      - run: go build hello.go
      - run: mv hello /go/src/github.com/dulrey/workspace
      - persist_to_workspace:
          root: /go/src/github.com/dulrey/workspace
          paths: hello
  test:
    executor: my-executor
    steps:
      - checkout
      - run: 
          name: go test
          command: go test -v ./...

workflows:
  build_test_docker_build_and_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
          requires:
            - test
          workspace-root: /go/src/github.com/dulrey/workspace
          account-url: AWS_ECR_ACCOUNT_URL
          attach-workspace: true
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: circleci-test
          path: /go/src/github.com/dulrey
          dockerfile: /go/src/github.com/dulrey/test-repo/Dockerfile
