version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dulrey/test-repo
    steps:
      - checkout
      - run:
          name: go build
          command: go build hello.go
  test:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: 
        name: go test
        command: go test -v ./...

workflows:
  build_and_push_image:
    jobs:
      - build
      - test
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          # profile-name: myProfileName
          region: AWS_REGION
          repo: circleci-test
