version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dulrey/test-repo
    steps:
      - checkout
      - run: 
          name: go get
          command: go get -v -t -d ./...
      - run: 
          name: go test
          command: go test -v ./...
      - run:
          name: go build
          command: go build hello.go
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build -t hello-image .
      - aws-s3/copy:
          from: test-repo
          to: 's3://circleci-test-dan'
orbs:
  aws-s3: circleci/aws-s3@1.0.15
